name = "Swift"
license = "MIT"
licenselink = "https://github.com/onweru/hugo-swift-theme/blob/master/LICENSE.md"
description = "A simple open source theme for publishing with hugo"
homepage = "https://github.com/onweru/hugo-swift-theme"
tags = ["blog", "clean", "responsive", "simple", "staticman"]
features = ["blog", "responsive", "staticman", "simple", "deeplinks" ]
min_version = 0.13

[author]
    name ="weru"
    homepage = "https://github.com/onweru/hugo-swift-theme"
